# mychart/values.yaml

nodeNames:
  - "node1"
  - "node2"

global:
  imagePullSecrets : []
  repository: "repo/bdortho"
  tag: "latest"
  pullPolicy: Always
  storageClass: "nfs-csi"
  TimeZone : "Europe/Paris" # Time Zone to elaborate the TTS
  TTS : "06:00" # Time To STOP
  BDORTHO_BUCKET : "/bucket" # Where is located the bucket (can be a local path or a remote path like s3://bucket)
  BDORTHO_SLACK_URL : "slack_webhook_url" # Slack webhook url to send notification

master :
  schedule: "0 20 * * *" # at 20:00
  failedJobsHistoryLimit : 1
  successfulJobsHistoryLimit : 1
  backoffLimit : 0
  autoRemoveJobAfter : 172800 # 2 days


worker: 
  storageSize : 50 # Gi, size of the pvc for each worker's workdir
  schedule: "3 20 * * *" # at 20:03
  failedJobsHistoryLimit : 1
  successfulJobsHistoryLimit : 1
  backoffLimit : 0
  jobs : 3



# default security context, run as non root uid 1000
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000