# mychart/values.yaml
fullnameOverride : ""
nameOverride: ""

global :
  secret: "default" # secret name to use for the slack webhook url

common:
  imagePullSecrets : []
  repository: "harbor.portal.kalisio.com/kalisio/bdortho"
  rcloneSecret : "rclone-config"
  tag: "latest"
  pullPolicy: Always
  storageClass: ""
  env :
    TIMEZONE : "Europe/Paris" # Time Zone to elaborate the TTS
    TTS : "06:00" # Time To STOP
    BDORTHO_SLACK_URL : 
      key : slack-webhook-url
    BDORTHO_BUCKET : "ovh:path/to/data/folder" # Where is located the bucket (can be a local path or a remote path like s3://bucket)


master :
  cron: "0 21 * * *" # at 21:00 UTC
  failedJobsHistoryLimit : 1
  successfulJobsHistoryLimit : 1
  backoffLimit : 0
  autoRemoveJobAfter : 172800 # 2 days


worker: 
  numberOfWorkers : 3 # Number of nodes in the cluster (excluding the master, exceeding the number of nodes will schedule multiple jobs on already scheduled nodes)
  storageSize : 50 # Gi, size of the pvc for each worker's workdir
  cron: "1 21 * * *" # at 21:01 UTC
  failedJobsHistoryLimit : 1
  successfulJobsHistoryLimit : 1
  backoffLimit : 0
  env :
    JOBS : "1" # Number of jobs to run in parallel on each worker (gdaltranslate)



# default security context, run as non root uid 1000
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000


