apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bdortho-bucket-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  storageClassName: nfs-csi

---