{{- range $index := until ($.Values.worker.numberOfWorkers | int)}}
{{- $index = add $index 1 }} # We need to start at 1

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bdortho-pvc-{{ $index }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.worker.storageSize }}Gi
  storageClassName: {{ $.Values.common.storageClass }}
  volumeMode: Filesystem
---
{{- end }}
