{{- $nodeNames := .Values.nodeNames }}
{{- range $nodeName := $nodeNames }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $nodeName }}-bdortho-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.worker.storageSize }}Gi
  storageClassName: {{ $.Values.global.storageClass }}
  volumeMode: Filesystem
---
{{- end }}
