apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kargo.names.name" . }}-update
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ $.Values.master.cron }}
  concurrencyPolicy : Forbid
  failedJobsHistoryLimit: {{ $.Values.master.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $.Values.master.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ $.Values.master.backoffLimit }}
      ttlSecondsAfterFinished: {{ .Values.master.autoRemoveJobAfter | default 172800 }} # 2 days
      template:
        spec:
          restartPolicy: Never
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}         

          {{- with .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: {{ include "kargo.names.name" . }}-update
            image: {{ $.Values.global.repository }}:{{ $.Values.global.tag | default "latest" }}
            imagePullPolicy: {{ $.Values.global.pullPolicy }}
            env:
            - name: VOLUMES
              value: "/data"
            - name: ROLE
              value: "master"
            {{- include "kargo.environment.render" (dict "env" $.Values.global.env "context" $) | indent 12 }}
            volumeMounts:
            {{- if $.Values.global.rcloneSecret }}
            - name: rclone-config
              mountPath: /.rclone.conf
              subPath: rclone.conf
              readOnly: true
            {{- end }}
        
{{- range $index := until ($.Values.worker.numberOfWorkers | int)}}
{{- $index = add $index 1 }} # We need to start at 1
            - name: bdortho-data-{{ $index }}
              mountPath: /data/{{ $index }}
{{- end }}
          volumes:
{{- range $index := until ($.Values.worker.numberOfWorkers | int)}}
{{- $index = add $index 1 }} # We need to start at 1
          - name: bdortho-data-{{ $index }}
            persistentVolumeClaim:
              claimName: bdortho-pvc-{{ $index }}
{{- end }}
          {{- if $.Values.global.rcloneSecret }}
          {{- include "kargo.rcloneConfig.renderVolume" ( dict "args" $.Values.global "context" $ ) | nindent 10 }}
          {{- end }}
          
          
