{{- $nodeNames := .Values.nodeNames }}
{{- range $nodeName := $nodeNames }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bd-ortho-{{ $nodeName }}-cronjob
spec:
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: bd-ortho-{{ $nodeName }}-pod
        spec:
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/hostname: {{ $nodeName }}
          containers:
          - name: bd-ortho-{{ $nodeName }}-container
            image: {{ $.Values.global.repository }}:{{ $.Values.global.tag }}
            imagePullPolicy: {{ $.Values.global.pullPolicy }}
            env:
            - name: BDORTHO_HOSTNAME
              value: {{ $nodeName }}
            - name: BDORTHO_BUCKET
              value:  {{ $.Values.global.BDORTHO_BUCKET }}
            - name: ROLE
              value: "worker"
            - name: TTS
              value: {{ $.Values.TTS }}
            - name: TimeZone
              value: {{ $.Values.global.TimeZone }}
            - name: JOBS
              value: {{ $.Values.worker.jobs | quote }}
            - name: BDORTHO_SLACK_URL
              value: {{ $.Values.global.BDORTHO_SLACK_URL }}
            - name: VOLUMES
              value: "/data"



            volumeMounts:
            - name: {{ $nodeName }}-bdortho-data
              mountPath: /data
            - name: bdortho-bucket
              mountPath: /bucket

          volumes:
          - name: {{ $nodeName }}-bdortho-data
            persistentVolumeClaim:
              claimName: {{ $nodeName }}-bdortho-pvc
          - name: bdortho-bucket
            persistentVolumeClaim:
              claimName: bdortho-bucket-pvc
--- # Necessary to create multiple cronjobs
{{- end }}
